//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_ASP_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogInfo
    {
        public int DogId { get; set; }
        public string DogName { get; set; }
        public Nullable<bool> DogGender { get; set; }
        public int categoryID { get; set; }
        public string DogImage { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
